# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               PokéMath 
tagline:             "Pokémon by the Numbers"
description:         "Math is great. Pokémon is great. There's a lot of hidden math in Pokémon - let's explore it!"
url:                 http://www.pokemath.com
baseurl:             ''
paginate:            5

